### ISSUE TITLE
Fix Charts tooltip

### ISSUE THREAD

**Issue by emibcn** [emibcn/covid#10]
Now, it shows each value with a text colored as the line/area corresponding to the value. Better use some typical legend style like the original.

### Now:
![image](https://user-images.githubusercontent.com/693791/95400835-f551c880-090b-11eb-858c-f0617c0a8718.png)

### Original (wanted, but using Material UI styles):
![image](https://user-images.githubusercontent.com/693791/95400878-11556a00-090c-11eb-9ea5-24d36bbd6887.png)

File: https://github.com/emibcn/covid/blob/master/app/src/Widget/Widgets/Chart/Chart.js

**Comment by SahanAmarsha** [comment]
Can I work on this issue

**Comment by emibcn** [comment]
Assigned! @SahanAmarsha

**Comment by SahanAmarsha** [comment]
Do I need to use material UI when implementing this?

**Comment by emibcn** [comment]
@SahanAmarsha Whenever useful and possible: yes, please.

**Comment by SahanAmarsha** [comment]
[![tooltip](https://user-images.githubusercontent.com/60227056/95661721-1d7d3980-0b4f-11eb-839d-66da78fc9603.JPG)
](url)

@emibcn I'm afraid I cant improve styling beyond here. If you have any resources please share with me.

**Comment by emibcn** [comment]
@SahanAmarsha I think you can use [Recharts Tooltip API](http://recharts.org/en-US/api/Tooltip) to change it's behaviour. I think `content` is the attribute can help us. The docs may not be as complete as it could be, so a `content={ (...allArgs) => {debugger; return null}}` may help to see what arguments it passes down. If you want more help/tips I can dig even deeper.

**Comment by SahanAmarsha** [comment]
Thanks, & Noted. I will look into these.
