### ISSUE TITLE
Fix Add button

### ISSUE THREAD

**Issue by emibcn** [emibcn/covid#11]
Current **Add** button is not as awesome as it could be ;P

### Current:
![image](https://user-images.githubusercontent.com/693791/95401052-89bc2b00-090c-11eb-8366-72a93cfea419.png)

### Proposal:
From https://material.io/design/color/applying-color-to-ui.html#attributes
![image](https://user-images.githubusercontent.com/693791/95401309-2a124f80-090d-11eb-9893-cc09728bece0.png)

File: https://github.com/emibcn/covid/blob/master/app/src/Widget/MenuAddWidget.jsx#L54

**Comment by ashish979** [comment]
Hi @emibcn 
can I take this one?

**Comment by emibcn** [comment]
It's yours!

**Comment by ashish979** [comment]
@emibcn Does this look ok?
![image](https://user-images.githubusercontent.com/7333996/95554986-bb2d1780-0a2e-11eb-825b-b6bfe0a1eef7.png)

**Comment by emibcn** [comment]
@ashish979 Looks great!

**Comment by ashish979** [comment]
Raised PR with the changes #22

**Comment by emibcn** [comment]
[Thanked!](https://github.com/emibcn/covid#thanks-to)

Great job!
