### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by emibcn** [emibcn/covid#14]
To help new comers contribute.

Features:
- Use plain English: contributors will normally be non-native English speakers.
- Be welcoming. 
- Simple: short and concise better than long. If needed, long texts will go into sub pages (for example, setting up development environment).
- Refer to [code of conduct](https://github.com/emibcn/covid/blob/master/CODE_OF_CONDUCT.md).
- Add some coding standards: indenting, preferred choices (for example: `const copied = [...original]` instead of `const copied = original.slice()`), etc
- More?

Note: There is some text already written in the [README.md](https://github.com/emibcn/covid/blob/master/README.md#contributing) file.

**Comment by PPInfy** [comment]
Taking this issue

**Comment by emibcn** [comment]
@PPInfy Assigned!

**Comment by PPInfy** [comment]
Check #15
