### ISSUE TITLE
Add some lateral margin to Slider on non-small devices

### ISSUE THREAD

**Issue by emibcn** [emibcn/covid#17]
On non-small devices, dates are shown and space is "cheaper". Add some margin between the slider and the buttons it has around, for devices grater than `md`.

Files:
- Add new CSS class for slider root: https://github.com/emibcn/covid/blob/master/app/src/Widget/List.jsx#L74
- Send class to slider with `root` key name: https://github.com/emibcn/covid/blob/master/app/src/Widget/List.jsx#L267
- Slider will apply sent classes (no need to change, I think): https://github.com/emibcn/covid/blob/master/app/src/Slider.jsx#L150

Source Slider docs: https://material-ui.com/api/slider/#css

**Comment by mblaul** [comment]
Mind if I take this one? 😀

**Comment by silenteyesoncode** [comment]
please let me know if i can work on it

**Comment by silenteyesoncode** [comment]
Yes I'm searching for any issues so to contribute

**Comment by emibcn** [comment]
@silenteyesoncode Do you want this one https://github.com/emibcn/covid/issues/23 ?

**Comment by silenteyesoncode** [comment]
> @silenteyesoncode Do you want this one https://github.com/emibcn/covid/issues/23 ?

Sure
