### ISSUE TITLE
Fix Polish translations of new strings

### ISSUE THREAD

**Issue by emibcn** [emibcn/covid#25]
There are some new strings in the app whose have already been translated to all languages but Polish.

File: https://github.com/emibcn/covid/blob/master/app/src/i18n/pl-pl.lang.js#L114

**Comment by emibcn** [comment]
@wikiyu ?

**Comment by magdalenapaluch** [comment]
I can take this if you want

**Comment by emibcn** [comment]
@magdalenapaluch Assigned to you!
