### ISSUE TITLE
Add Language selector

### ISSUE THREAD

**Issue by emibcn** [emibcn/covid#3]
Let the user select his/her preferred language:
- Language selector component could be placed directly into [the menu](https://github.com/emibcn/covid/blob/master/app/src/Menu.jsx#L159)
- It already has a data source at [App's state](https://github.com/emibcn/covid/blob/master/app/src/App.js#L61) passed all way down to the [Menu](https://github.com/emibcn/covid/blob/master/app/src/App.js#L120)
- If changed, all app is already translated into the selected language

**Comment by Abhijith126** [comment]
can I take this?

**Comment by emibcn** [comment]
@Abhijith126  Of course!

**Comment by Abhijith126** [comment]
Please feel free to assign this ticket to me. I will fork and start work on this.

**Comment by emibcn** [comment]
> Please feel free to assign this ticket to me. I will fork and start work on this.

Done!

**Comment by Abhijith126** [comment]
@emibcn, I have added a new Menu, Language after About. 
Once selected the below dialog appears. Is this the expected behavior?
Also, how do you want to display the list of Languages?. 
Let me know your thoughts on this,
![image](https://user-images.githubusercontent.com/9048589/94999085-86efcc00-05d4-11eb-81bd-ff3e5050f3d0.png)

**Comment by emibcn** [comment]
Looks good!

A couple of thoughts:
- Use some Material UI element (for example, https://material-ui.com/components/radio-buttons/ )
- Show actual [language name](https://github.com/Abhijith126/covid/blob/d1c72a7710010de52b4d3c7473a0def36b2ef4f8/app/src/Language.jsx#L13) instead of code and remove duplicates, something like (not tested; would need to add `name` attribute on each language):
```javascript
const keys = Object.keys(available);
keys
  // From https://www.javascripttutorial.net/array/javascript-remove-duplicates-from-array/
  .filter((key, index) => {
     return keys.indexOf(key) !== index;
  })
```

**Comment by Abhijith126** [comment]
I have created a PR with the changes and added translations for words like language based on google translate. This needs to be verified. 
Please check and let me know if any changes are required.

**Comment by emibcn** [comment]
Commented on https://github.com/emibcn/covid/pull/19#pullrequestreview-505078924
