### ISSUE TITLE
Move Backends logic to a Data Context Provider/Consumer logic (allow easy backend adding)

### ISSUE THREAD

**Issue by emibcn** [emibcn/covid#33]
Currently, backends are instantiated and central handled directly from `Widget/List` component, and then passed each backend index to all widgets (kind of...).

### Proposal
- Create a Context Provider/Consumer pair for each backend
- Compose all providers into a single BackendsProvider, and add it to `Widget/List` parent (`App`)
- Add backend consumers to each component/widget that needs it

**Comment by sebas-alarconr** [comment]
Hi, I think I can handle this :)

**Comment by emibcn** [comment]
Hi @sebas-alarconr !
Just assigned the issue to you.

This issue is a bit complicated. If in any doubt (like how to do something or which implementations take within all the possible ones), don't hesitate to comment it here.

**Comment by sebas-alarconr** [comment]
@emibcn thanks :)

Btw, already created a PR, I think it is covering the initial proposal, but let me know if you imagined it different.

Since I saw some spots where the backend data is being re-generated I provided the data handlers through the Providers.

If you want me to add / modify anything, just let me know.

(I can even add JSDocs if you want)

**Comment by emibcn** [comment]
Great!! This is in the line I was thinking about. This can be further improved here or on next issues/PRs, as you prefer.

Things to improve even more:
- [ ] Stop passing backend indexes from Widget/List to the actual widgets: they'll get them from consumer. Ensure they all do it cleanly (sorry about differences between widgets, this project is growing fast).
- [ ] Include in the HOC a condition to show a `<Loading/>` instead of wrapped component while index is not loaded (and subscribe to index download, passing it to wrapped component once loaded). `Backend/Map` uses a static index: might be needed to create an auto-resolved Promise to homogenize interfaces.
- [ ] Include in the HOC the possibility to subscribe to data by props. For example, in `Widgets/Bcn/Widget.jsx`, we will be able to remove almost all class methods from `ChartDataHandler` class (hence simplifying new widgets creation and maintenance ). Here, the consumer will need to detect if `this.prop.dataset` is defined and, if yes, use it to download data and show a `<Loading/>` while loading that.

Tell me if you prefer to merge what you've already done and create new (sub)issues or do it right here.

## About JSDocs
It would be great, even if only this part is done. We'll need to link it to a workflow to update project's wiki (using GitHub API?) or some `docs/` directory to automatically update it. Once merged, we can create a new issue for that.

**Comment by emibcn** [comment]
FYI: Done in issue https://github.com/emibcn/covid/issues/40 with PR https://github.com/emibcn/covid/pull/47 .

> Great!! This is in the line I was thinking about. This can be further improved here or on next issues/PRs, as you prefer.
> 
> Things to improve even more:
> 
> * [x]  Stop passing backend indexes from Widget/List to the actual widgets: they'll get them from consumer. Ensure they all do it cleanly (sorry about differences between widgets, this project is growing fast).
> * [x]  Include in the HOC a condition to show a `<Loading/>` instead of wrapped component while index is not loaded (and subscribe to index download, passing it to wrapped component once loaded). `Backend/Map` uses a static index: might be needed to create an auto-resolved Promise to homogenize interfaces.
> * [x]  Include in the HOC the possibility to subscribe to data by props. For example, in `Widgets/Bcn/Widget.jsx`, we will be able to remove almost all class methods from `ChartDataHandler` class (hence simplifying new widgets creation and maintenance ). Here, the consumer will need to detect if `this.prop.dataset` is defined and, if yes, use it to download data and show a `<Loading/>` while loading that.
> 
> Tell me if you prefer to merge what you've already done and create new (sub)issues or do it right here.
> 
> ## About JSDocs
> It would be great, even if only this part is done. We'll need to link it to a workflow to update project's wiki (using GitHub API?) or some `docs/` directory to automatically update it. Once merged, we can create a new issue for that.

**Comment by emibcn** [comment]
@sebas-alarconr I think you might like to take a look into the code that tests yours: https://github.com/emibcn/covid/blob/add-tests/app/src/Backend/Base/ContextCreator.test.jsx (not yet merged into master).

Well, you created a context for each backend. I abstracted it into a `ContextCreator`, which basically does the same, but is meant to be used from each backend handler to create the exported functions/components.
