### ISSUE TITLE
Add Theme selector

### ISSUE THREAD

**Issue by emibcn** [emibcn/covid#5]
Let the user select his/her preferred theme from `light` or `dark`:
- Theme selector component could be placed directly into [the menu](https://github.com/emibcn/covid/blob/master/app/src/Menu.jsx#L159)
- It already has a data source at [App's state](https://github.com/emibcn/covid/blob/master/app/src/App.js#L62) passed all way down to the [Menu](https://github.com/emibcn/covid/blob/master/app/src/App.js#L123)
- If changed, all app is shown with the selected theme
- Theme initial preference is taken from browser' [MediaQuery selector `(prefers-color-scheme: dark)`](https://github.com/emibcn/covid/blob/master/app/src/Dashboard.jsx#L50). If none is defined, `light` is taken by default.

**Comment by greyGroot** [comment]
hi, i would like to work on this one. Could you please assign it to me? I will work on it during hacktoberfest.

**Comment by emibcn** [comment]
@greyGroot All yours!!

**Comment by emibcn** [comment]
Hello @greyGroot !! Any news on this issue? Do you need any help?

**Comment by greyGroot** [comment]
OMG, i totally forgot about this issue. @emibcn i'm really sorry. Sorry and now i don't have free time for this. Sorry.

**Comment by emibcn** [comment]
Don't worry, it's not that bad ;)

If you have some code, please, push to your cloned repo and open a PR. This way, me or someone else will be able to finish it. If not, never mind, me or someone else will write it all :P
