### ISSUE TITLE
UI/UX: Rethink Slider and Map Widget Tooltip component for small screens

### ISSUE THREAD

**Issue by emibcn** [emibcn/covid#6]
When using the app in small screens, the _sticky_ Slider may cause some problems when zooming in/out, scrolling and trying to read Map Widget' regions tooltip.

![image](https://user-images.githubusercontent.com/693791/94370774-2eab5c80-00f2-11eb-929a-352ad32a3f59.png)

If you are not a developer but want to participate in Hacktoberfest, you can submit mockups as PR to the `badges` branch.

**Comment by mandy6720** [comment]
Could I grab this one?

**Comment by emibcn** [comment]
@mandy6720  It's yours!

**Comment by mandy6720** [comment]
@emibcn Is there a trick to getting it to run locally? I cd-ed into app and did an npm install but when i go to localhost:3000/covid, i just see this
<img width="1145" alt="Screen Shot 2020-10-07 at 12 00 51 PM" src="https://user-images.githubusercontent.com/11623748/95356548-66ea3200-088c-11eb-8c76-79c297a1b317.png">

**Comment by emibcn** [comment]
Hummm... I think I need to write a Howto for all this things. There is an environmental variable I forgot to document somewhere. It's in the workflow. They are used as URL base to get the JSON data.

Depends on how you're environment is, you'll need to declare them differently. In my case, I use `docker` and `docker-compose`. In the Workflow, a workflow env variable is used. This is done to use different backend endpoints, for testing and developing purposes. As you are not developing that part, you can just set the production server:

```bash
REACT_APP_MAP_STATIC_HOST=https://emibcn.github.io/covid-data/Maps
```
If you are using linux, you can modify your local copy of `package.json` (do not commit it...), with something like:
```json
  "scripts": {
    "start": "REACT_APP_MAP_STATIC_HOST=https://emibcn.github.io/covid-data/Maps react-scripts start",
```

Or use `cross-env` as explained here: https://stackoverflow.com/questions/25112510/how-to-set-environment-variables-from-within-package-json

**Comment by reachtokish** [comment]
Hey @emibcn I'm trying to setup this project in my local. Did this following step but app is not starting still
```
REACT_APP_MAP_STATIC_HOST=https://emibcn.github.io/covid-data/Maps
```
I'm using MAC OS. Any other steps do I need to do?

Able to see this following screen

![image](https://user-images.githubusercontent.com/10685261/95412470-a6755480-0946-11eb-8c23-1e5ad579f6f8.png)

Kindly help me out. Thanks

**Comment by emibcn** [comment]
@reachtokish @mandy6720 

Hi both!

I've just published a commit where default values are supplied for those variables directly in their `Backend/{Charts,Maps}` handlers, so if a developer wants to change them, it's possible, but dont worry about that to the rest.

In short, it should be easier to install it locally.

Please, test and confirm.

**Comment by mandy6720** [comment]
Works great! Thanks @emibcn
